In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [3]:
A = np.random.randn(100)

平均值 = 0  標準差 =1

In [4]:
A = A*10 + 50

平均值50 標準差10

In [5]:
A

array([46.58696773, 38.59914597, 68.91442596, 46.63845278, 57.92374243,
       60.06682912, 48.94971787, 50.39755771, 52.13580054, 57.22976573,
       43.37938133, 55.02828742, 63.70863355, 61.5722256 , 50.33764353,
       37.03312278, 55.71030512, 66.48771829, 49.82608111, 49.5912473 ,
       57.59430191, 52.17667293, 70.71782883, 50.45130657, 49.77194949,
       32.00534775, 63.37040423, 58.69455328, 57.01500327, 32.74569927,
       61.86433173, 52.33221836, 47.86462   , 74.67519754, 42.43917453,
       53.00630156, 49.47223203, 61.26140487, 51.66704584, 55.46763473,
       44.52561704, 39.55779831, 45.43403462, 65.29681447, 51.73970065,
       60.83917681, 46.34238421, 55.39847942, 55.01633668, 45.69265598,
       48.25691604, 41.15924138, 43.39118625, 51.04545874, 56.62524536,
       64.50521086, 43.32864058, 57.42162166, 43.23655636, 59.17780419,
       60.95537839, 39.39120685, 64.44275212, 47.02605752, 66.4662689 ,
       51.85691802, 43.22063476, 52.54910119, 53.05652785, 39.22

In [7]:
A.shape

(100,)

In [10]:
A.shape = (4,25)

In [11]:
A

array([[46.58696773, 38.59914597, 68.91442596, 46.63845278, 57.92374243,
        60.06682912, 48.94971787, 50.39755771, 52.13580054, 57.22976573,
        43.37938133, 55.02828742, 63.70863355, 61.5722256 , 50.33764353,
        37.03312278, 55.71030512, 66.48771829, 49.82608111, 49.5912473 ,
        57.59430191, 52.17667293, 70.71782883, 50.45130657, 49.77194949],
       [32.00534775, 63.37040423, 58.69455328, 57.01500327, 32.74569927,
        61.86433173, 52.33221836, 47.86462   , 74.67519754, 42.43917453,
        53.00630156, 49.47223203, 61.26140487, 51.66704584, 55.46763473,
        44.52561704, 39.55779831, 45.43403462, 65.29681447, 51.73970065,
        60.83917681, 46.34238421, 55.39847942, 55.01633668, 45.69265598],
       [48.25691604, 41.15924138, 43.39118625, 51.04545874, 56.62524536,
        64.50521086, 43.32864058, 57.42162166, 43.23655636, 59.17780419,
        60.95537839, 39.39120685, 64.44275212, 47.02605752, 66.4662689 ,
        51.85691802, 43.22063476, 52.54910119, 53

分成4組 每組25人

In [12]:
A.reshape(25,4)

array([[46.58696773, 38.59914597, 68.91442596, 46.63845278],
       [57.92374243, 60.06682912, 48.94971787, 50.39755771],
       [52.13580054, 57.22976573, 43.37938133, 55.02828742],
       [63.70863355, 61.5722256 , 50.33764353, 37.03312278],
       [55.71030512, 66.48771829, 49.82608111, 49.5912473 ],
       [57.59430191, 52.17667293, 70.71782883, 50.45130657],
       [49.77194949, 32.00534775, 63.37040423, 58.69455328],
       [57.01500327, 32.74569927, 61.86433173, 52.33221836],
       [47.86462   , 74.67519754, 42.43917453, 53.00630156],
       [49.47223203, 61.26140487, 51.66704584, 55.46763473],
       [44.52561704, 39.55779831, 45.43403462, 65.29681447],
       [51.73970065, 60.83917681, 46.34238421, 55.39847942],
       [55.01633668, 45.69265598, 48.25691604, 41.15924138],
       [43.39118625, 51.04545874, 56.62524536, 64.50521086],
       [43.32864058, 57.42162166, 43.23655636, 59.17780419],
       [60.95537839, 39.39120685, 64.44275212, 47.02605752],
       [66.4662689 , 51.

分成25組 每組4人

In [13]:
A

array([[46.58696773, 38.59914597, 68.91442596, 46.63845278, 57.92374243,
        60.06682912, 48.94971787, 50.39755771, 52.13580054, 57.22976573,
        43.37938133, 55.02828742, 63.70863355, 61.5722256 , 50.33764353,
        37.03312278, 55.71030512, 66.48771829, 49.82608111, 49.5912473 ,
        57.59430191, 52.17667293, 70.71782883, 50.45130657, 49.77194949],
       [32.00534775, 63.37040423, 58.69455328, 57.01500327, 32.74569927,
        61.86433173, 52.33221836, 47.86462   , 74.67519754, 42.43917453,
        53.00630156, 49.47223203, 61.26140487, 51.66704584, 55.46763473,
        44.52561704, 39.55779831, 45.43403462, 65.29681447, 51.73970065,
        60.83917681, 46.34238421, 55.39847942, 55.01633668, 45.69265598],
       [48.25691604, 41.15924138, 43.39118625, 51.04545874, 56.62524536,
        64.50521086, 43.32864058, 57.42162166, 43.23655636, 59.17780419,
        60.95537839, 39.39120685, 64.44275212, 47.02605752, 66.4662689 ,
        51.85691802, 43.22063476, 52.54910119, 53

A沒有改變 仍然是25x4 reshape沒有回傳

In [16]:
A = A.reshape(25,4)

In [17]:
A

array([[46.58696773, 38.59914597, 68.91442596, 46.63845278],
       [57.92374243, 60.06682912, 48.94971787, 50.39755771],
       [52.13580054, 57.22976573, 43.37938133, 55.02828742],
       [63.70863355, 61.5722256 , 50.33764353, 37.03312278],
       [55.71030512, 66.48771829, 49.82608111, 49.5912473 ],
       [57.59430191, 52.17667293, 70.71782883, 50.45130657],
       [49.77194949, 32.00534775, 63.37040423, 58.69455328],
       [57.01500327, 32.74569927, 61.86433173, 52.33221836],
       [47.86462   , 74.67519754, 42.43917453, 53.00630156],
       [49.47223203, 61.26140487, 51.66704584, 55.46763473],
       [44.52561704, 39.55779831, 45.43403462, 65.29681447],
       [51.73970065, 60.83917681, 46.34238421, 55.39847942],
       [55.01633668, 45.69265598, 48.25691604, 41.15924138],
       [43.39118625, 51.04545874, 56.62524536, 64.50521086],
       [43.32864058, 57.42162166, 43.23655636, 59.17780419],
       [60.95537839, 39.39120685, 64.44275212, 47.02605752],
       [66.4662689 , 51.